# Site settings
title: "Burak ÖZDAMAR | CV"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Burak ÖZDAMAR, PhD"
resume_title:                   "Physicist specialized in Material Science"
resume_title_fr:                "Physicien spéc. en Science des Matériaux"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "burak.ozdamar@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "06 41 92 40 92"
resume_contact_address:         "Évry, 91000, FR"

resume_header_contact_info:     "Évry, 91000, FR • +33641924092 • burak.ozdamar [at] gmail (.) com"
display_header_contact_info:    "true"

resume_header_intro: "<p>8 years of experience in molecular modeling and computational simulations focusing on ab-initio molecular dynamics.</p>"
resume_header_intro_fr: "<p>8 ans d'expérience en modélisation moléculaire et simulations computationnelles axées sur la dynamique moléculaire ab-initio.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_dribbble_url:          "https://dribbble.com/jag"
  resume_github_url:            "https://github.com/burakozdamar"
  resume_linkedin_url:          "https://www.linkedin.com/in/burak-ozdamar-202863a8/"
  resume_twitter_url:           "https://orcid.org/0000-0001-7185-1978"
  #resume_facebook_url:          "insert Facebook URL here"
  #resume_instagram_url:         "insert your Instagram URL here"
  resume_email:                 "mailto:burak.ozdamar@gmail.com"
  resume_medium_url:            "https://scholar.google.com/citations?user=BMkPc5AAAAAJ&hl=en"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
